language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly
 
matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm-nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mkdir -p build/logs

after_script:
 - php vendor/bin/coveralls -v
